version: '3.8'
name: PasswordManager-Compose

services:
  #passwordmanager.api:
  #  image: ${DOCKER_REGISTRY-}passwordmanagerapi
  #  build:
  #    context: .
  #    dockerfile: src/PasswordManager.API/Dockerfile

  #identityserver:
  #  image: ${DOCKER_REGISTRY-}identityserver
  #  build:
  #    context: .
  #    dockerfile: src/IdentityServer/Dockerfile


  #passwordmanager.ui:
  #  image: ${DOCKER_REGISTRY-}passwordmanagerui
  #  build:
  #    context: .
  #    dockerfile: src/PasswordManager.UI/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5

  apmserver:
    image: docker.elastic.co/apm/apm-server:7.17.5

  elastic-enterprise-search:
    image: docker.elastic.co/enterprise-search/enterprise-search:7.17.5

  jaeger:
    image: jaegertracing/all-in-one:latest

  consul:
    image: consul

volumes:
  elasticsearch-data: